### ISSUE TITLE
Driver installation issue

### ISSUE THREAD

**Issue by kadament** [morrownr/8812au#29]
Hi, I'm having an issue installing this driver. It installed and worked for a few days, but after a reboot it was uninstalled for some reason and now won't install properly again. Modinfo 8812au.ko | grep 010E, returns with the alias showing it has been installed, but then it isn't appearing with list mod. I downloaded it a few weeks ago from this repo and installing it using sudo make, sudo make install. And it completes without errors. The only other thing I thought was strange is that there is no 8812au.conf in the folder with the other config files. Any help would be really appreciated! Thanks.

**Comment by morrownr** [comment]
Hello @kadament 

I'm going to point out in a friendly manner that it is highly unlikely you would be posting this issue if you followed the installation instructions. I have put a lot of work into making and testing the installation instructions and scripts that actually do the installation. The way you installed works fine until your distro decides it is time for a kernel upgrade. My installation instructions make use of dkms so that the installation of a new kernel is handled automatically.

Recommend you run $ sudo ./remove-driver.sh and then delete the 8812au directory followed by a reboot followed by reading and following the posted installation instructions.

Let me know how it goes.

Nick
